- Configuration/Yaml/FormSetup.yaml
This PR adds a missing translation file to translate labels in FormEngine.
> [BUGFIX] Add missing translation file for labels in FormEngine

- Classes/Domain/Finishers/ConsentFinisher.php
This PR adds the current server request object to the `FluidEmail` object.
> [BUGFIX] Provide current server request in consent mail

- Classes/Configuration/Extension.php
- composer.json
- ext_localconf.php
This PR adds a configuration for the scheduler garbage collection task. It deletes expired consents.
> [FEATURE] Provide configuration for garbage collection via scheduler

- Classes/Controller/ConsentController.php
This PR fixes a bug that occurs if an error is rendered by the `ConsentController` when the `consent` template variable has not been assigned yet.
> [BUGFIX] Assign `consent` template variable early

- Classes/Domain/Finishers/ConsentFinisher.php
- composer.json
- phpstan.neon
This PR solves the problem that uploaded files could not be JSON-encoded. Instead of encoding the object, the file UID is now persisted.
> [BUGFIX] Properly JSON-encode uploaded files

- Classes/Domain/Finishers/ConsentFinisher.php
This PR fixes the initialization of the injected `FlashMessageFinisher` inside `ConsentFinisher`. The initialization of finishers extending `AbstractFinisher` changed with [#94317](https://forge.typo3.org/issues/94317) aka https://github.com/TYPO3/typo3/commit/962042cec5134816c961d92d90b59175274bc9e8.
> [BUGFIX] Handle changed instantiation of FlashMessageFinisher

- Classes/Domain/Finishers/ConsentFinisher.php
- composer.json
This PR adds the `FormRuntime` object as template variable to the `ConsentMail` templates.
> [FEATURE] Provide FormRuntime object in consent mail template

- Configuration/Yaml/FormSetup.yaml
> [BUGFIX] Include translation files in FormEngine

- Resources/Private/Partials/Link/Approve.txt
- Resources/Private/Partials/Link/Dismiss.txt
This PR fixes an issue with links in plain-text mails. Prior to this change, all links were escaped, resulting in malicious URLs:
```diff
-/confirmation?tx_formconsent_consent[action]=approve&amp;tx_formconsent_consent[hash]=foo&amp;tx_formconsent_consent[email]=user@example.com
+/confirmation?tx_formconsent_consent[action]=approve&tx_formconsent_consent[hash]=foo&tx_formconsent_consent[email]=user@example.com
```
⚠️ If partials were overridden, this change must be applied manually.
> [BUGFIX] Avoid escaping of links in plain-text mails

- .ddev/docker-compose.selenium.yaml
This PR exchanges the Selenium image used for acceptance tests.
```diff
-selenium/standalone-chrome-debug:3.13.0-argon
+seleniarm/standalone-chromium:4.1.2-20220227
```
The new image supports ARM as well, adding support for Apple M1 computers.
Related issue: SeleniumHQ/docker-selenium/issues/1076
> [BUGFIX] Switch to arm-compatible Selenium image

- README.md
This PR adds a short notice about alternative installation via TER to the `README.md` file.
> [DOCS] Mention download via TER

- .github/release.yml
- .github/workflows/release.yaml
This PR enables GitHub's [automatic generation of release notes](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes). Release notes will no longer generated manually in CI, but rather automatically via GitHub. An appropriate release notes configuration has been added.
> [FEATURE] Enable GitHub's automatic generation of release notes

- Classes/Controller/ConsentController.php
- Classes/Event/DismissConsentEvent.php
- Tests/Unit/Event/DismissConsentEventTest.php
This PR streamlines the possibilities of `ApproveConsentEvent` and `DismissConsentEvent`. Both events are now able to receive custom responses that are evaluated in the dispatching `ConsentController`.
This is a follow-up to #24.
> [FEATURE] Allow passing custom responses via DismissConsentEvent

- Tests/Acceptance/Backend/ConsentDataElementCest.php
A Backend acceptance test is skipped as it is not compatible with the current version of symfony/rate-limiter.
Related: symfony/symfony#45925
> [BUGFIX] Skip one acceptance test for PHP 8.1

- Resources/Private/Language/locallang.xlf
- Resources/Private/Language/locallang_be.xlf
- Resources/Private/Language/locallang_db.xlf
- Resources/Private/Language/locallang_form.xlf
This PR streamlines all locallang*.xlf files with the XLIFF 1.2 standard, which is currently supported by TYPO3 CMS.
> [TASK] Streamline locallang*.xlf files with XLIFF 1.2

- .ddev/config.yaml
- .github/workflows/cgl.yaml
- CONTRIBUTING.md
- README.md
- codeception.yml
- composer.json
This PR streamlines and automates local development environment preparation. It is now executed on each `ddev start`, `composer install` and `composer update`. This includes:
> [BUGFIX] Automate local development environment preparation

- .github/dependabot.yml
- .github/release.yml
This PR enables automated Dependabot updates for GitHub Actions.
> [FEATURE] Enable Dependabot for GitHub Actions

- Configuration/Yaml/FormSetup.yaml
- Tests/Acceptance/Backend/FormEditorCest.php
The `implementationClassName` configuration was only applied in FE context. This lead to an exception in form preview mode within BE form editor.
Resolves: #55
> [BUGFIX] Provide `implementationClassName` in BE finishers definition

- .github/workflows/cgl.yaml
- .github/workflows/tests.yaml
This PR limits workflow runs to the `main` and `develop` branches when triggered via `push` event. This avoids concurrent workflow runs if an active pull request exists.
> [BUGFIX] Avoid concurrent workflow runs in pull requests

- Classes/Domain/Finishers/ConsentFinisher.php
- README.md
- Tests/Acceptance/Data/Fileadmin/form_definitions/contact.form.yaml
- Tests/Acceptance/Data/Fixtures/fe_users.sql
- Tests/Acceptance/Frontend/ConsentFinisherCest.php
With this PR, the last inserted consent is now populated with the finisher variable provider. Consumers can access the consent in `.form.yaml` configuration via `{Consent.lastInsertedConsent}` or in finisher context via
```php
/** @var \EliasHaeussler\Typo3FormConsent\Domain\Model\Consent|null $lastInsertedConsent */
$lastInsertedConsent = $this->finisherContext->getFinisherVariableProvider()->get(
$this->shortFinisherIdentifier,
'lastInsertedConsent'
);
```
---
Resolves: #61
> [FEATURE] Populate last inserted consent with finisher variable provider

- Classes/Domain/Factory/ConsentFactory.php
- Classes/Domain/Finishers/ConsentFinisher.php
- Classes/Event/ModifyConsentEvent.php
- Classes/Event/ModifyConsentMailEvent.php
- Tests/Unit/Event/ModifyConsentEventTest.php
- Tests/Unit/Event/ModifyConsentMailEventTest.php
With this PR, the current `FormRuntime` instance is now populated with these events:
* `EliasHaeussler\Typo3FormConsent\Event\ModifyConsentEvent`
* `EliasHaeussler\Typo3FormConsent\Event\ModifyConsentMailEvent`
In an appropriate event listener, calling `$event->getFormRuntime()` accesses the current `FormRuntime` instance. This allows for further manipulation of the current `Consent`, e.g. by adding additional data extracted form a current form element state.
⚠️ This PR is considered **breaking**, because the constructor signature of mentioned classes has changed.
---
Related: #62
> [!!!][FEATURE] Make FormRuntime available via ModifyConsent events

- composer.json
With TYPO3/typo3@9f933f2, a new `FormRequestHandler` was introduced. It provides a new centralized place to render forms. With this change, all logic that resided in the `<formvh:render>` view helper was moved to the new class. However, the new request handler does now actively hide the current content object renderer instance. This means, EXT:form_consent will no longer be able to fetch the current content element UID since this is only available in the original `ContentObjectRenderer`.
Until this bug is fixed, installation of TYPO3 11.5.13 is not possible since it limits the features provided by EXT:form_consent and therefore leads to unexpected behavior of the extension.
⚠️ Consumers making use of this extension should **consider downgrading to TYPO3 11.5.12** if they rely on the full …
> [BUGFIX] Disallow installation of TYPO3 11.5.13

- Classes/Configuration/Configuration.php
- Classes/Configuration/Icon.php
- Classes/Controller/ConsentController.php
- Classes/Domain/Factory/ConsentFactory.php
- Classes/Domain/Finishers/ConsentFinisher.php
- Classes/Domain/Finishers/FinisherOptions.php
- Classes/Domain/Model/Consent.php
- Classes/Event/Listener/InvokeFinishersListener.php
- Classes/Http/StringableResponse.php
- Classes/Service/HashService.php
- Classes/Type/ConsentStateType.php
- Classes/Type/Transformer/FormRequestTypeTransformer.php
- Classes/Type/Transformer/FormValuesTypeTransformer.php
- Classes/Updates/MigrateConsentStateUpgradeWizard.php
- Tests/Acceptance/Frontend/ConsentFinisherCest.php
- Tests/Acceptance/Support/Helper/Email.php
- Tests/Acceptance/Support/Helper/Form.php
- Tests/Functional/ExpressionLanguage/FunctionsProvider/ConsentConditionFunctionsProviderTest.php
With TYPO3/coding-standards#31, yoda-style conditions were explicitly disabled. This PR aligns the code base with the updated coding-standards package.
> [BUGFIX] Align with latest changes in typo3/coding-standards

- .github/dependabot.yml
- .github/workflows/cgl.yaml
- .github/workflows/tests.yaml
- README.md
With this PR, support for the `develop` branch is dropped. Instead, the `main` branch will now be the main branch.
> [TASK] Drop support for `develop` branch

- ext_emconf.php
As a follow-up to #69, installation of this extension via extension manager is now also prohibited via `ext_emconf.php` for TYPO3 11.5.13 and later. Reasons are explained in said PR.
> [BUGFIX] Avoid installation of TYPO3 11.5.13+ via ext_emconf.php

- README.md
- composer.json
- ext_emconf.php
The initial TYPO3 patch released with 11.5.13 (outlined in #69) has been reverted and included in the latest TYPO3 release 11.5.16. Therefore, 11.5.16 and further versions can now be used together with EXT:form_consent. However, affected versions 11.5.13, 11.5.14 and 11.5.15 are added to `conflicts` to avoid usage of EXT:form_consent along with those TYPO3 versions.
Related: #69
> [BUGFIX] Allow installation of EXT:form >= 11.5.16

- Classes/Updates/MigrateConsentStateUpgradeWizard.php
If no more legacy columns are available in the database, the upgrade wizard to migrate consent state must not be executed.
Resolves: #79
> [BUGFIX] Skip upgrade wizard if no more legacy columns are to be migrated

- .github/workflows/release.yaml
With GitHub [deprecating the `set-output` commands in GitHub workflows](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/), the new `$GITHUB_OUTPUT` variable needs to be used instead.
> [BUGFIX] Replace deprecated job outputs in GitHub workflows

- .github/workflows/tests.yaml
The `jonaseberle/github-action-setup-ddev` action was replaced by `ddev/github-action-setup-ddev` and is now deprecated. Thus, we switch to the new, official action.
> [TASK] Switch to `ddev/github-action-setup-ddev`

- Tests/Functional/Configuration/ConfigurationTest.php
- Tests/Functional/Configuration/IconTest.php
- Tests/Functional/Configuration/LocalizationTest.php
- Tests/Functional/Domain/Finishers/FinisherOptionsTest.php
- Tests/Functional/Domain/Repository/ConsentRepositoryTest.php
- Tests/Functional/ExpressionLanguage/FunctionsProvider/ConsentConditionFunctionsProviderTest.php
- Tests/Functional/Service/HashServiceTest.php
- Tests/Functional/Type/Transformer/FormRequestTypeTransformerTest.php
- Tests/Functional/Type/Transformer/FormValuesTypeTransformerTest.php
- Tests/Functional/Widget/Provider/ConsentChartDataProviderTest.php
- Tests/Unit/Configuration/IconTest.php
- Tests/Unit/Domain/Model/ConsentTest.php
- Tests/Unit/Event/ApproveConsentEventTest.php
- Tests/Unit/Event/DismissConsentEventTest.php
- Tests/Unit/Event/GenerateHashEventTest.php
- Tests/Unit/Event/ModifyConsentEventTest.php
- Tests/Unit/Event/ModifyConsentMailEventTest.php
- Tests/Unit/Exception/NotAllowedExceptionTest.php
- Tests/Unit/Exception/UnsupportedTypeExceptionTest.php
- Tests/Unit/Registry/ConsentManagerRegistryTest.php
- Tests/Unit/Type/ConsentStateTypeTest.php
- Tests/Unit/Type/JsonTypeTest.php
- Tests/Unit/Type/Transformer/TypeTransformerFactoryTest.php
This PR adds PHPUnit's `CoversClass` attribute to all tests.
> [TASK] Use `CoversClass` attribute in tests

- Configuration/Services.yaml
Since TYPO3 fetches the related event class via reflection, it can be safely omitted from listener registration in `Services.yaml`.
> [TASK] Omit event class from listener registration

- Classes/DependencyInjection/DashboardServicesConfigurator.php
Dashboard widgets need proper dependency injection, therefore autowiring custom widgets is necessary unless dependencies are not injected manually. This seems to have changed with TYPO3 v12. With this PR, autowiring for class dependencies of the dashboard widget is now explicitly enabled.
> [BUGFIX] Autowire class dependencies of dashboard widget

- Tests/Acceptance/Backend/ApprovedConsentsWidgetCest.php
- Tests/Acceptance/Backend/ConsentDataElementCest.php
- Tests/Acceptance/Backend/FormEditorCest.php
- Tests/Acceptance/Support/Enums/Selectors.php
This PR moves all DOM selectors used in acceptance tests to a dedicated `Selectors` enum.
> [TASK] Move selectors in acceptance tests to dedicated enum

- Classes/Configuration/Configuration.php
- Classes/Configuration/Icon.php
- Classes/Configuration/Localization.php
- Classes/Domain/Finishers/FinisherOptions.php
- Classes/Extension.php
- Configuration/TCA/Overrides/sys_template.php
- Configuration/TCA/Overrides/tt_content.php
- Tests/Functional/Configuration/ConfigurationTest.php
- ext_localconf.php
- rector.php
The `Extension` class is now located in the root namespace of the extension.
> [TASK] Move Extension class to extension root namespace

- Classes/Configuration/Configuration.php
- Classes/Type/Transformer/FormValuesTypeTransformer.php
- Tests/Functional/Configuration/ConfigurationTest.php
- Tests/Functional/Type/Transformer/FormValuesTypeTransformerTest.php
This PR rewrites the `Configuration` class to use dependency injection. As a result, static methods must now be called on object level and consumers must inject the `Configuration` class properly.
> [!!!][TASK] Use DI in `Configuration` class

- Classes/Type/Transformer/FormRequestTypeTransformer.php
- Classes/Type/Transformer/FormValuesTypeTransformer.php
- Classes/Type/Transformer/TypeTransformerInterface.php
As a follow-up to #119, this PR drops the `TypeTransformerInterface::getName()` from said interface and its implementations.
> [!!!][TASK] Drop TypeTransformerInterface::getName()

- Classes/Type/Transformer/FormRequestTypeTransformer.php
- Classes/Type/Transformer/FormValuesTypeTransformer.php
- Classes/Type/Transformer/TypeTransformer.php
- phpstan-baseline.neon
This PR removes the `Interface` suffix from `TypeTransformerInterface`.
> [!!!][TASK] Rename TypeTransformerInterface to TypeTransformer

- codeception.yml
This PR adds the `--no-sandbox` chrome option to stabilize acceptance tests made with the `WebDriver` module, as suggested [here](https://stackoverflow.com/a/53970825).
> [BUGFIX] Stabilize WebDriver capabilities by using `--no-sandbox`

- Classes/Type/Transformer/FormRequestTypeTransformer.php
- Tests/Acceptance/Frontend/Domain/Finishers/ConsentFinisherCest.php
This PR fixes an issue where the plugin namespace of EXT:form (`tx_form_formframework`) was not prepended to the uploaded files stored in original request parameters. This bug happened since TYPO3 12.0.0, respectively typo3/typo3@02198ea257b9f03f910b3b120392ab63fe792a8b.
Resolves: #138
> [BUGFIX] Assure plugin namespace in original request parameters

- .ddev/commands/web/init-typo3
- composer.json
This PR fixes a bug with latest xdebug version where a globally configured `XDEBUG_MODE` is not properly respected. It can be reverted once a dedicated xdebug release is pushed and included in DDEV.
> [BUGFIX] Assure XDEBUG_MODE is set when running tests with coverage

- composer.json
- composer.lock
The dependency to `nikic/php-parser` was added in an earlier stage to assure compatibility with lowest version constraints. However, it is no longer necessary to define it, therefore it's now dropped.
> [TASK] Remove explicit dependency to "nikic/php-parser"

- Classes/Domain/Factory/ConsentFactory.php
- Classes/Domain/Finishers/ConsentFinisher.php
- Classes/Event/ModifyConsentEvent.php
- Documentation/DeveloperCorner/ConsentFactory.rst
- Documentation/Migration/Index.rst
- Tests/Unit/Event/ModifyConsentEventTest.php
This PR changes the components shipped by the `ModifyConsentEvent` to provide the overall `FinisherContext` instead of only the underlying `FormRuntime`. This, for example, allows to cancel current finisher execution by calling `$event->getFinisherContext()->cancel()`. Since the method signature of `ConsentFactory::createFromForm()` (which is public API) is modified, this change is considered breaking.
> [!!!][FEATURE] Provide FinisherContext in ModifyConsentEvent

- Classes/Domain/Finishers/ConsentFinisher.php
- Documentation/DeveloperCorner/Events.rst
- Tests/Functional/Domain/Finishers/ConsentFinisherTest.php
- composer.json
- composer.lock
- phpstan-baseline.neon
This PR adds a little modification to the consent process. By accessing the `FinisherContext` form the `ModifyConsentEvent`, one can cancel current finisher execution and therefore stop further processing of the generated consent. The consent itself is not persisted and no consent mail is sent.
> [FEATURE] Exit early if finisher execution is cancelled

- Classes/Domain/Finishers/ConsentFinisher.php
- Classes/Domain/Finishers/FinisherOptions.php
- Configuration/Yaml/FormSetup.yaml
- Documentation/Configuration/FormFinisherConfiguration.rst
- Documentation/Usage/ConsentFinisher.rst
- Resources/Private/Language/locallang_form.xlf
- Tests/Acceptance/Data/Fileadmin/form_definitions/contact-confirmation-approve-variant.form.yaml
- Tests/Acceptance/Data/Fileadmin/form_definitions/contact-confirmation-dismiss-variant.form.yaml
- Tests/Acceptance/Data/Fileadmin/form_definitions/contact-email-approve-variant.form.yaml
- Tests/Acceptance/Data/Fileadmin/form_definitions/contact-invalid-closure-approve-variant.form.yaml
- Tests/Acceptance/Data/Fileadmin/form_definitions/contact-invalid-closure-dismiss-variant.form.yaml
- Tests/Acceptance/Data/Fileadmin/form_definitions/contact-invalid.form.yaml
- Tests/Acceptance/Data/Fileadmin/form_definitions/contact-redirect-approve-dismiss-variant.form.yaml
- Tests/Acceptance/Data/Fileadmin/form_definitions/contact-redirect-approve-variant.form.yaml
- Tests/Acceptance/Data/Fileadmin/form_definitions/contact-redirect-dismiss-variant.form.yaml
- Tests/Acceptance/Data/Fileadmin/form_definitions/contact-v2.form.yaml
- Tests/Acceptance/Data/Fileadmin/form_definitions/contact.form.yaml
- Tests/Acceptance/Frontend/Domain/Finishers/ConsentFinisherCest.php
- Tests/Functional/Domain/Finishers/ConsentFinisherTest.php
- Tests/Functional/Domain/Finishers/FinisherOptionsTest.php
This PR adds support for a `Reply-To` recipient in consent mail.
> [FEATURE] Allow configuration of `Reply-To` recipients in consent mail

- Configuration/TCA/tx_formconsent_domain_model_consent.php
This PR removes a useless switch for `eval` with `required` in a table column configuration for TYPO3 < v12.
> [TASK] Avoid useless switch for eval "required" in TYPO3 < v12

- Classes/Domain/Finishers/FinisherOptions.php
- Classes/Extension.php
- Tests/Functional/Domain/Finishers/FinisherOptionsTest.php
It turned out that the default storage pid configured as TypoScript constant `plugin.tx_formconsent.persistence.storagePid` was never respected. This PR fixes this behavior and explicitly looks up this value if no storage pid is configured in a form.
> [BUGFIX] Respect default storage pid if storage pid is not set in form

- Configuration/Sets/FormConsent/config.yaml
- Configuration/Sets/FormConsent/constants.typoscript
- Configuration/Sets/FormConsent/settings.definitions.yaml
- Configuration/Sets/FormConsent/setup.typoscript
- Documentation/Configuration/FormFinisherConfiguration.rst
- Documentation/Configuration/Index.rst
- Documentation/Configuration/SiteSetConfiguration.rst
- Documentation/Index.rst
- Documentation/Installation/Index.rst
- Documentation/Usage/Index.rst
- Tests/Build/Configuration/sites/main/config.yaml
This PR adds a new site set for use with TYPO3 >= 13.1.
TODO:
> [FEATURE] Add support for site sets (TYPO3 >= v13.1)

- Classes/Domain/Finishers/FinisherOptions.php
- Tests/Functional/Domain/Finishers/FinisherOptionsTest.php
These paths are registered with with numeric indices which indicate the priority. The higher the number, the higher the priority of the path for lookup.
For TYPO3 before version 12 this priority must be implemented manually by sorting paths by their keys.
See https://github.com/TYPO3/typo3/blob/v12.4.20/typo3/sysext/form/Classes/Domain/Finishers/EmailFinisher.php#L172
And https://github.com/TYPO3/typo3/commit/c68090f2e802e363869dc3d2f79f2b51f3e5f8be
> Respect order of template/partial/layout root paths

- .ddev/addon-metadata/ddev-selenium-standalone-chrome/manifest.yaml
- .ddev/docker-compose.selenium-chrome.yaml
This PR updates the `ddev/ddev-selenium-standalone-chrome` add-on to the latest version.
> [TASK] Update `ddev-selenium-standalone-chrome` add-on to v1.1.0

- Classes/Extension.php
- Tests/CGL/typoscript-lint.yml
- ext_localconf.php
- ext_typoscript_setup.typoscript
This PR moves global TypoScript configuration from `ext_typoscript_setup.typoscript` to `ext_localconf.php` which is required when using site sets.
> [BUGFIX] Assure global TypoScript can be loaded with site sets

- Tests/Functional/Domain/Finishers/ConsentFinisherTest.php
- Tests/Functional/Domain/Repository/ConsentRepositoryTest.php
- Tests/Functional/ExtbaseRequestAwareFunctionalTestCase.php
The example site configuration used in functional tests defines dependencies to other sites sets. With recent implementations, an exception is thrown if these extensions are not active. Hence, we must enable them in the appropriate functional tests.
> [BUGFIX] Enable extensions of dependent site sets in functional tests

- Tests/Unit/Compatibility/Migration/HmacHashMigrationTest.php
- composer.json
- composer.lock
- phpunit.unit.xml
This pull request includes several changes to the unit tests and configuration files to improve compatibility and functionality. The key changes involve adding a new PHPUnit extension, updating dependencies, and cleaning up test conditions.
Improvements to unit tests:
* [`Tests/Unit/Compatibility/Migration/HmacHashMigrationTest.php`](diffhunk://#diff-6997c201162997911d4952a3a8249baced3146f5e90e3558aa6730a8e6e4368eR26-L28): Added `PHPUnitAttributes\Attribute\RequiresPackage` attribute to ensure tests are only run with TYPO3 v13 or higher, and removed the conditional check in the `setUp` method. [[1]](diffhunk://#diff-6997c201162997911d4952a3a8249baced3146f5e90e3558aa6730a8e6e4368eR26-L28) [[2]](diffhunk://#diff-6997c201162997911d4952a3a8249baced3146f5e90e3558aa6730a8e6e4368eR38-R39) …
> [TASK] Use `phpunit-attributes` package to skip a test
